
version: 2

sources:
  - name: atomic
    schema: atomic
    tables:
      - name: events
  - name: derived
    schema:  "{{target.schema ~ '_derived'}}"
    database: "{{ var('snowplow__database', target.database) if target.type not in ['databricks', 'spark'] else var('snowplow__databricks_catalog', 'hive_metastore') if target.type in ['databricks'] else var('snowplow__atomic_schema', 'atomic') }}"
    tables:
      - name: snowplow_unified_conversions
        description: An incremental table which contains all relevant fields for unique conversion events.
      - name: snowplow_unified_views 
      - name: snowplow_unified_sessions

models:
  - name: snowplow_attribution_path_summary
    description: For each unique path, a summary of associated conversions, non conversions and revenue
    columns:
      - name: transformed_path
        description: "> delimited path summary"
      - name: conversions
        description: Count of conversions for this path
      - name: non_conversions
        description: Count of non-conversions for path
      - name: revenue
        description: Revenue associated with the conversion
      - name: direct_display_other_organic_search_paid_search_referral
        description: These columns may be created dynamically

  - name: snowplow_attribution_paths_to_conversion
    description: Customer id and the the paths the customer has followed that have lead to conversion
    columns:
      - name: customer_id
        description: Id for the customer (identified or cookie)
      - name: cv_tstamp
        description: The derived_tstamp of the conversion event
      - name: revenue
        description: Revenue associated with the conversion
      - name: path
        description: Path to conversion (> delimited)
      - name: transformed_path
        description: Transformations applied to "path" above

  - name: snowplow_attribution_paths_to_non_conversion
    description: Customer id and the the paths the customer has followed that have not lead to conversion
    columns:
      - name: customer_id
        description: Id for the customer (identified or cookie)
      - name: path
        description: Path to conversion (> delimited)
      - name: transformed_path
        description: Transformations applied to "path" above

  - name: snowplow_attribution_campaign_attributions
    description: By campaign path and conversion level incremental table that attributes the conversion value based on various algorythms
    columns:
      - name: composite_key
        description: The primary key of the table comprised of the conversion event_id + campaign path name (e.g. Organic_Search) + source_index
      - name: event_id
        description: A UUID for each event e.g. ‘c6ef3124-b53a-4b13-a233-0088f79dcbcb’
      - name: customer_id
        description: Id for the customer (identified or cookie)
      - name: cv_tstamp
        description: The derived_tstamp of the conversion event
      - name: revenue
        description: Revenue associated with the conversion
      - name: campaign_path
        description: Each path flattened from campaign_transformed_path that lead to a conversion
      - name: source_index
        description: The index which denotes the path order from first to last before conversion starting from 0
      - name: first_touch_attribution
        description: The revenue attribution value for a given path with first_touch attribution logic applied, meaning that the first touch-point will get all the attribution. 
      - name: last_touch_attribution
        description: The revenue attribution value for a given path with last_touch attribution logic applied, meaning that the last touch-point will get all the attribution.
      - name: linear_attribution
        description: The revenue attribution value for a given path with linear attribution logic applied, meaning that the revenue is split equally among all the touch-points.
      - name: position_based_attribution
        description: The revenue attribution value for a given path with position_based attribution logic applied, meaning that the first and last touch-points will get 40% of the attribution, the remaining should get the equal split between the remaining 20%

  - name: snowplow_attribution_channel_attributions
    description: By channel path and conversion level incremental table that attributes the conversion value based on various algorythms
    columns:
      - name: composite_key
        description: The primary key of the table comprised of the conversion event_id + channel path name (e.g. Organic_Search) + source_index
      - name: event_id
        description: A UUID for each event e.g. ‘c6ef3124-b53a-4b13-a233-0088f79dcbcb’
      - name: customer_id
        description: Id for the customer (identified or cookie)
      - name: cv_tstamp
        description: The derived_tstamp of the conversion event
      - name: revenue
        description: Revenue associated with the conversion
      - name: channel_path
        description: Each path flattened from channel_transformed_path that lead to a conversion
      - name: source_index
        description: The index which denotes the path order from first to last before conversion starting from 0
      - name: first_touch_attribution
        description: The revenue attribution value for a given path with first_touch attribution logic applied, meaning that the first touch-point will get all the attribution. 
      - name: last_touch_attribution
        description: The revenue attribution value for a given path with last_touch attribution logic applied, meaning that the last touch-point will get all the attribution.
      - name: linear_attribution
        description: The revenue attribution value for a given path with linear attribution logic applied, meaning that the revenue is split equally among all the touch-points.
      - name: position_based_attribution
        description: The revenue attribution value for a given path with position_based attribution logic applied, meaning that the first and last touch-points will get 40% of the attribution, the remaining should get the equal split between the remaining 20%

  - name: roas
    description: The user defined report table to calculate ROIs
    columns:
      - name: path_type
        description: Type of path - channel or campaign
      - name: path
        description: The type of channel or campaign to calculate the ROI and attribution for
      - name: conversions
        description: The number of conversions
      - name: revenue
        description: Revenue associated with the conversion
      - name: spend
        description: The marketing spend
      - name: ROAS
        description: Return on advertising spend
      